### ISSUE TITLE
AUT-CEIT

### ISSUE THREAD

**Issue by 1995parham** [aut-ce/HowToGraduateFromAUT#1]
سلام دکتر !
آقا ما یک ریپو زدیم برای دانشکده دوست داشتی این را اونجا به اشتراک بگذار 👍

**Comment by smahmadpanah** [comment]
سلام

ایمیلت رو گرفتم.
من یه کم سرم خلوت شه و به سر و سامان برسم، سعی میکنم یه کارهایی بکنم.

سید محمد مهدی احمدپناه
Seyed Mohammad Mehdi Ahmadpanah http://ceit.aut.ac.ir/~ahmadpanah

**Comment by 1995parham** [comment]
ممنونم ! امیدوارم همه چیز خوب بشه
