### ISSUE TITLE
سی دی برای کتابخانه ارشد

### ISSUE THREAD

**Issue by aryadegari** [aut-ce/HowToGraduateFromAUT#3]
گفته شده برای کتابخانه سی دی نیاز است که گویا نیست! بررسی و ویرایش شود.

**Comment by smahmadpanah** [comment]
لطفا خودت ویرایش کن :)

**Comment by hadifar** [comment]
بله درسته نیاز نیست.

**Comment by smahmadpanah** [comment]
لطفا ویرایش بفرمایید مهندس!
