### ISSUE TITLE
مشکل باز شدن PDF

### ISSUE THREAD

**Issue by saeedsamie** [aut-ce/HowToGraduateFromAUT#6]
دمتون گرم بچه ها خیلی متن خوب و به درد بخوریه مخصوصا تو این وضعیت که هیچکسی درست راهنمایی نمیکنه 
برای من بسیار کاربردی بود
فقط HowToGradFromBSc-CovidEdition.pdf باز نمیشد که عجیب بود بررسیش بکنید لطفا
![image](https://user-images.githubusercontent.com/13640371/104889663-c4aa1200-5983-11eb-8117-1ca395073099.png)

**Comment by Arya11b** [comment]
الان با این لینک میارید باز نمیکنه؟
[https://github.com/aut-ce/HowToGraduateFromAUT/blob/master/HowToGradFromBSc-CovidEdition.pdf](https://github.com/aut-ce/HowToGraduateFromAUT/blob/master/HowToGradFromBSc-CovidEdition.pdf)
من تست کردم مشکلی نداره فایل، با یه نرم افزار دیگه (یا با خود مرورگر) هم امتحان کنید
اگه باز جواب نداد از فایل وورد هم میتونید استفاده کنید
