### ISSUE TITLE
azad sazi madrak

### ISSUE THREAD

**Issue by shayanthrn** [aut-ce/HowToGraduateFromAUT#7]
please add how to release our degree as soon as possible:(.

**Comment by aryadegari** [comment]
با سلام، من سال ها پیش از مطلب [آزاد کردن مدرک و دریافت دانشنامه برای عپلای](https://vrgl.ir/3gYha) برای آزاد کردن مدارکم استفاده کردم. لطفا اگر تفاوتی در فرآیند هست در پست اصلی یا اینجا ذکر کنید.
